# Generated by Django 3.0 on 2022-09-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_taken', models.TimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=True)),
                ('time_stamp', models.TimeField(auto_now_add=True)),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='chat.Userprofile')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chat.Userprofile')),
            ],
            options={
                'ordering': ('time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='chat.Userprofile')),
            ],
        ),
    ]
